CREATE TABLE pricing_tiers (
  id               INT PRIMARY KEY AUTO_INCREMENT,
  tour_id          INT(11) NOT NULL,
  group_size       VARCHAR(100) NOT NULL,
  price_per_person DECIMAL(10,2) NOT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pricing_tiers_tour FOREIGN KEY (tour_id) REFERENCES tours(tour_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE pricing_notes (
  id         INT PRIMARY KEY AUTO_INCREMENT,
  tour_id    INT(11) NOT NULL,
  note       TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pricing_notes_tour FOREIGN KEY (tour_id) REFERENCES tours(tour_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_
