CREATE TABLE IF NOT EXISTS home_partners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    web_url VARCHAR(255) DEFAULT NULL,
    logo_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;